### ISSUE TITLE
Make an optimization to check the user queue

### ISSUE THREAD

**Issue by XaartlonDreezey** [ton-blockchain/token-bridge-solidity#4]
Considering that the bridge is a critical zone where there should be no prerequisites for the loss of funds, it is necessary to optimize access to the transfer of coins through the bridge. In the code, I saw that you are checking the request stack to solve the problem with the queue. But why? In my opinion, you need to serve the first comer, without validation. Otherwise, we won't be able to handle an impromptu stress attack when many users want to use the bridge. My recommendation is to simplify the validation of users at the entrance when transferring coins.

 for (uint256 i = 0; i < signum; i++) {
            address signer = signatures[i].signer;
            require(isOracle[signer], "Unauthorized signer");
            uint256 next_signer = uint256(uint160(signer));
            require(next_signer > last_signer, "Signatures are not sorted");
            last_signer = next_signer;
            checkSignature(digest, signatures[i]);

My addr: EQAwnYKcC3FLcSES-bjcT5mIydT-RRxdRtuhYQwKU-dQlAc9

**Comment by tolya-yanot** [comment]
In the code the oracle signatures are checked.
