### ISSUE TITLE
Separation of an external method, creation of a private method to block funds before transferring them to another network

### ISSUE THREAD

**Issue by XaartlonDreezey** [ton-blockchain/token-bridge-solidity#5]
I think that blocking a certain number of coins should be done in the internal function of the contract. For security reasons, it is better not to expose the lock of funds to the external environment, because another smart contract can call this function and interrupt it. Make an internal method, and then transfer the remaining amount of funds from it, which will be sent to the network using an external method.

) external {
        require(allowLock, "Lock is currently disabled");
        require(token != address(0), "lock: wrong token address");
        require(token != address(0x582d872A1B094FC48F5DE31D3B73F2D9bE47def1), "lock wrapped toncoin");
        require(token != address(0x76A797A59Ba2C17726896976B7B3747BfD1d220f), "lock wrapped toncoin");
        require(!checkTokenIsWrappedJetton(token), "lock wrapped jetton");

        uint256 totalSupply = IERC20(token).totalSupply();
        require(totalSupply <= 2 ** 120 - 1, "Max totalSupply 2 ** 120 - 1");

        require(amount <= 2 ** 100, "Max amount 2 ** 100");

        uint256 oldBalance = IERC20(token).balanceOf(address(this));

        IERC20(token).safeTransferFrom(msg.sender, address(this), amount);

        uint256 newBalance = IERC20(token).balanceOf(address(this));

        require(newBalance > oldBalance, "newBalance must be greater than oldBalance");
------------------------separate this---------------------------------------------------------
        emit Lock(
            msg.sender,
            token,
            to_address_hash,
            newBalance - oldBalance,
            ERC20(token).decimals()
        );
    }

My addr: EQAwnYKcC3FLcSES-bjcT5mIydT-RRxdRtuhYQwKU-dQlAc9

Thanks for your attention :)

**Comment by eliot58** [comment]
what third party contract is SafeERC20 there

**Comment by XaartlonDreezey** [comment]
I meant that the external method implies the possibility of receiving commands from other contracts. It would be nice to reduce the chances of external influence when funds are blocked. Simply put, we allow what will definitely be allowed, we prohibit what is better to be banned. The majority of bridge breaks is that circumstances arise that violate the operation of the contract, or rather the main mechanisms.

**Comment by tolya-yanot** [comment]
We don't see any problem here. Please describe the bug or attack vector in detail

**Comment by XaartlonDreezey** [comment]
Wrapping a certain number of tokens is a process that does not require external influence. Why then make this function external? I would suggest splitting this block of code into two parts: one external function to access destination addresses. Another internal function is the blocking of funds. This action is necessary to isolate visibility fields. By isolating the functional part of a smart contract (in fact, a smart contract is a bridge), we deprive the environment of external attack vectors. It will complicate the code, yes, but this complication will lead to a better structure. Structure plays an important role in smart contracts.
